name: flutter_application_1
description: Um novo projeto Flutter

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  permission_handler: ^11.3.1
  flutter_local_notifications: ^17.0.0
  flutter:
    sdk: flutter
    
    
  table_calendar: ^3.0.9
  url_launcher: ^6.3.0
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  

  # Firebase (versões compatíveis entre si)
  firebase_core: ^4.2.0
  firebase_auth: ^6.1.1
  cloud_firestore: ^6.0.3
  firebase_storage: ^13.0.3
  intl: ^0.18.1

  # Escolher imagem da galeria
  image_picker: ^1.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/logo.jpeg
